name: quest-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=quest
  app:
    image: quest-nest-api:latest
    ports:
      - '3000:3000'   
    environment: 
      DATABASE_URL: "postgres://docker:docker@pg:5432/quest"    